<?php

use Esheinc\AuthPackage\Models\country;
use Illuminate\Database\Seeder;


class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
                    country::create(['name' => 'Afghanistan', 'iso' => 'AF']);
                    country::create(['name' => 'Åland Islands', 'iso' => 'AX']);
                    country::create(['name' => 'Albania', 'iso' => 'AL']);
                    country::create(['name' => 'Algeria', 'iso' => 'DZ']);
                    country::create(['name' => 'American Samoa', 'iso' => 'AS']);
                    country::create(['name' => 'Andorra', 'iso' => 'AD']);
                    country::create(['name' => 'Angola', 'iso' => 'AO']);
                    country::create(['name' => 'Anguilla', 'iso' => 'AI']);
                    country::create(['name' => 'Antarctica', 'iso' => 'AQ']);
                    country::create(['name' => 'Antigua and Barbuda', 'iso' => 'AG']);
                    country::create(['name' => 'Argentina', 'iso' => 'AR']);
                    country::create(['name' => 'Armenia', 'iso' => 'AM']);
                    country::create(['name' => 'Aruba', 'iso' => 'AW']);
                    country::create(['name' => 'Australia', 'iso' => 'AU']);
                    country::create(['name' => 'Austria', 'iso' => 'AT']);
                    country::create(['name' => 'Azerbaijan', 'iso' => 'AZ']);
                    country::create(['name' => 'Bahamas', 'iso' => 'BS']);
                    country::create(['name' => 'Bahrain', 'iso' => 'BH']);
                    country::create(['name' => 'Bangladesh', 'iso' => 'BD']);
                    country::create(['name' => 'Barbados', 'iso' => 'BB']);
                    country::create(['name' => 'Belarus', 'iso' => 'BY']);
                    country::create(['name' => 'Belgium', 'iso' => 'BE']);
                    country::create(['name' => 'Belize', 'iso' => 'BZ']);
                    country::create(['name' => 'Benin', 'iso' => 'BJ']);
                    country::create(['name' => 'Bermuda', 'iso' => 'BM']);
                    country::create(['name' => 'Bhutan', 'iso' => 'BT']);
                    country::create(['name' => 'Bolivia, Plurinational State of', 'iso' => 'BO']);
                    country::create(['name' => 'Bonaire, Sint Eustatius and Saba', 'iso' => 'BQ']);
                    country::create(['name' => 'Bosnia and Herzegovina', 'iso' => 'BA']);
                    country::create(['name' => 'Botswana', 'iso' => 'BW']);
                    country::create(['name' => 'Bouvet Island', 'iso' => 'BV']);
                    country::create(['name' => 'Brazil', 'iso' => 'BR']);
                    country::create(['name' => 'British Indian Ocean Territory', 'iso' => 'IO']);
                    country::create(['name' => 'Brunei Darussalam', 'iso' => 'BN']);
                    country::create(['name' => 'Bulgaria', 'iso' => 'BG']);
                    country::create(['name' => 'Burkina Faso', 'iso' => 'BF']);
                    country::create(['name' => 'Burundi', 'iso' => 'BI']);
                    country::create(['name' => 'Cambodia', 'iso' => 'KH']);
                    country::create(['name' => 'Cameroon', 'iso' => 'CM']);
                    country::create(['name' => 'Canada', 'iso' => 'CA']);
                    country::create(['name' => 'Cape Verde', 'iso' => 'CV']);
                    country::create(['name' => 'Cayman Islands', 'iso' => 'KY']);
                    country::create(['name' => 'Central African Republic', 'iso' => 'CF']);
                    country::create(['name' => 'Chad', 'iso' => 'TD']);
                    country::create(['name' => 'Chile', 'iso' => 'CL']);
                    country::create(['name' => 'China', 'iso' => 'CN']);
                    country::create(['name' => 'Christmas Island', 'iso' => 'CX']);
                    country::create(['name' => 'Cocos (Keeling); Islands', 'iso' => 'CC']);
                    country::create(['name' => 'Colombia', 'iso' => 'CO']);
                    country::create(['name' => 'Comoros', 'iso' => 'KM']);
                    country::create(['name' => 'Congo', 'iso' => 'CG']);
                    country::create(['name' => 'Congo, the Democratic Republic of the', 'iso' => 'CD']);
                    country::create(['name' => 'Cook Islands', 'iso' => 'CK']);
                    country::create(['name' => 'Costa Rica', 'iso' => 'CR']);
                    country::create(['name' => 'Côte d\'Ivoire', 'iso' => 'CI']);
                    country::create(['name' => 'Croatia', 'iso' => 'HR']);
                    country::create(['name' => 'Cuba', 'iso' => 'CU']);
                    country::create(['name' => 'Curaçao', 'iso' => 'CW']);
                    country::create(['name' => 'Cyprus', 'iso' => 'CY']);
                    country::create(['name' => 'Czech Republic', 'iso' => 'CZ']);
                    country::create(['name' => 'Denmark', 'iso' => 'DK']);
                    country::create(['name' => 'Djibouti', 'iso' => 'DJ']);
                    country::create(['name' => 'Dominica', 'iso' => 'DM']);
                    country::create(['name' => 'Dominican Republic', 'iso' => 'DO']);
                    country::create(['name' => 'Ecuador', 'iso' => 'EC']);
                    country::create(['name' => 'Egypt', 'iso' => 'EG']);
                    country::create(['name' => 'El Salvador', 'iso' => 'SV']);
                    country::create(['name' => 'Equatorial Guinea', 'iso' => 'GQ']);
                    country::create(['name' => 'Eritrea', 'iso' => 'ER']);
                    country::create(['name' => 'Estonia', 'iso' => 'EE']);
                    country::create(['name' => 'Ethiopia', 'iso' => 'ET']);
                    country::create(['name' => 'Falkland Islands (Malvinas);', 'iso' => 'FK']);
                    country::create(['name' => 'Faroe Islands', 'iso' => 'FO']);
                    country::create(['name' => 'Fiji', 'iso' => 'FJ']);
                    country::create(['name' => 'Finland', 'iso' => 'FI']);
                    country::create(['name' => 'France', 'iso' => 'FR']);
                    country::create(['name' => 'French Guiana', 'iso' => 'GF']);
                    country::create(['name' => 'French Polynesia', 'iso' => 'PF']);
                    country::create(['name' => 'French Southern Territories', 'iso' => 'TF']);
                    country::create(['name' => 'Gabon', 'iso' => 'GA']);
                    country::create(['name' => 'Gambia', 'iso' => 'GM']);
                    country::create(['name' => 'Georgia', 'iso' => 'GE']);
                    country::create(['name' => 'Germany', 'iso' => 'DE']);
                    country::create(['name' => 'Ghana', 'iso' => 'GH']);
                    country::create(['name' => 'Gibraltar', 'iso' => 'GI']);
                    country::create(['name' => 'Greece', 'iso' => 'GR']);
                    country::create(['name' => 'Greenland', 'iso' => 'GL']);
                    country::create(['name' => 'Grenada', 'iso' => 'GD']);
                    country::create(['name' => 'Guadeloupe', 'iso' => 'GP']);
                    country::create(['name' => 'Guam', 'iso' => 'GU']);
                    country::create(['name' => 'Guatemala', 'iso' => 'GT']);
                    country::create(['name' => 'Guernsey', 'iso' => 'GG']);
                    country::create(['name' => 'Guinea', 'iso' => 'GN']);
                    country::create(['name' => 'Guinea-Bissau', 'iso' => 'GW']);
                    country::create(['name' => 'Guyana', 'iso' => 'GY']);
                    country::create(['name' => 'Haiti', 'iso' => 'HT']);
                    country::create(['name' => 'Heard Island and McDonald Mcdonald Islands', 'iso' => 'HM']);
                    country::create(['name' => 'Holy See (Vatican City State);', 'iso' => 'VA']);
                    country::create(['name' => 'Honduras', 'iso' => 'HN']);
                    country::create(['name' => 'Hong Kong', 'iso' => 'HK']);
                    country::create(['name' => 'Hungary', 'iso' => 'HU']);
                    country::create(['name' => 'Iceland', 'iso' => 'IS']);
                    country::create(['name' => 'India', 'iso' => 'IN']);
                    country::create(['name' => 'Indonesia', 'iso' => 'ID']);
                    country::create(['name' => 'Iran, Islamic Republic of', 'iso' => 'IR']);
                    country::create(['name' => 'Iraq', 'iso' => 'IQ']);
                    country::create(['name' => 'Ireland', 'iso' => 'IE']);
                    country::create(['name' => 'Isle of Man', 'iso' => 'IM']);
                    country::create(['name' => 'Israel', 'iso' => 'IL']);
                    country::create(['name' => 'Italy', 'iso' => 'IT']);
                    country::create(['name' => 'Jamaica', 'iso' => 'JM']);
                    country::create(['name' => 'Japan', 'iso' => 'JP']);
                    country::create(['name' => 'Jersey', 'iso' => 'JE']);
                    country::create(['name' => 'Jordan', 'iso' => 'JO']);
                    country::create(['name' => 'Kazakhstan', 'iso' => 'KZ']);
                    country::create(['name' => 'Kenya', 'iso' => 'KE']);
                    country::create(['name' => 'Kiribati', 'iso' => 'KI']);
                    country::create(['name' => 'Korea, Democratic People\'s Republic of', 'iso' => 'KP']);
                    country::create(['name' => 'Korea, Republic of', 'iso' => 'KR']);
                    country::create(['name' => 'Kuwait', 'iso' => 'KW']);
                    country::create(['name' => 'Kyrgyzstan', 'iso' => 'KG']);
                    country::create(['name' => 'Lao People\'s Democratic Republic', 'iso' => 'LA']);
                    country::create(['name' => 'Latvia', 'iso' => 'LV']);
                    country::create(['name' => 'Lebanon', 'iso' => 'LB']);
                    country::create(['name' => 'Lesotho', 'iso' => 'LS']);
                    country::create(['name' => 'Liberia', 'iso' => 'LR']);
                    country::create(['name' => 'Libya', 'iso' => 'LY']);
                    country::create(['name' => 'Liechtenstein', 'iso' => 'LI']);
                    country::create(['name' => 'Lithuania', 'iso' => 'LT']);
                    country::create(['name' => 'Luxembourg', 'iso' => 'LU']);
                    country::create(['name' => 'Macao', 'iso' => 'MO']);
                    country::create(['name' => 'Macedonia, the Former Yugoslav Republic of', 'iso' => 'MK']);
                    country::create(['name' => 'Madagascar', 'iso' => 'MG']);
                    country::create(['name' => 'Malawi', 'iso' => 'MW']);
                    country::create(['name' => 'Malaysia', 'iso' => 'MY']);
                    country::create(['name' => 'Maldives', 'iso' => 'MV']);
                    country::create(['name' => 'Mali', 'iso' => 'ML']);
                    country::create(['name' => 'Malta', 'iso' => 'MT']);
                    country::create(['name' => 'Marshall Islands', 'iso' => 'MH']);
                    country::create(['name' => 'Martinique', 'iso' => 'MQ']);
                    country::create(['name' => 'Mauritania', 'iso' => 'MR']);
                    country::create(['name' => 'Mauritius', 'iso' => 'MU']);
                    country::create(['name' => 'Mayotte', 'iso' => 'YT']);
                    country::create(['name' => 'Mexico', 'iso' => 'MX']);
                    country::create(['name' => 'Micronesia, Federated States of', 'iso' => 'FM']);
                    country::create(['name' => 'Moldova, Republic of', 'iso' => 'MD']);
                    country::create(['name' => 'Monaco', 'iso' => 'MC']);
                    country::create(['name' => 'Mongolia', 'iso' => 'MN']);
                    country::create(['name' => 'Montenegro', 'iso' => 'ME']);
                    country::create(['name' => 'Montserrat', 'iso' => 'MS']);
                    country::create(['name' => 'Morocco', 'iso' => 'MA']);
                    country::create(['name' => 'Mozambique', 'iso' => 'MZ']);
                    country::create(['name' => 'Myanmar', 'iso' => 'MM']);
                    country::create(['name' => 'Namibia', 'iso' => 'NA']);
                    country::create(['name' => 'Nauru', 'iso' => 'NR']);
                    country::create(['name' => 'Nepal', 'iso' => 'NP']);
                    country::create(['name' => 'Netherlands', 'iso' => 'NL']);
                    country::create(['name' => 'New Caledonia', 'iso' => 'NC']);
                    country::create(['name' => 'New Zealand', 'iso' => 'NZ']);
                    country::create(['name' => 'Nicaragua', 'iso' => 'NI']);
                    country::create(['name' => 'Niger', 'iso' => 'NE']);
                    country::create(['name' => 'Nigeria', 'iso' => 'NG']);
                    country::create(['name' => 'Niue', 'iso' => 'NU']);
                    country::create(['name' => 'Norfolk Island', 'iso' => 'NF']);
                    country::create(['name' => 'Northern Mariana Islands', 'iso' => 'MP']);
                    country::create(['name' => 'Norway', 'iso' => 'NO']);
                    country::create(['name' => 'Oman', 'iso' => 'OM']);
                    country::create(['name' => 'Pakistan', 'iso' => 'PK']);
                    country::create(['name' => 'Palau', 'iso' => 'PW']);
                    country::create(['name' => 'Palestine, State of', 'iso' => 'PS']);
                    country::create(['name' => 'Panama', 'iso' => 'PA']);
                    country::create(['name' => 'Papua New Guinea', 'iso' => 'PG']);
                    country::create(['name' => 'Paraguay', 'iso' => 'PY']);
                    country::create(['name' => 'Peru', 'iso' => 'PE']);
                    country::create(['name' => 'Philippines', 'iso' => 'PH']);
                    country::create(['name' => 'Pitcairn', 'iso' => 'PN']);
                    country::create(['name' => 'Poland', 'iso' => 'PL']);
                    country::create(['name' => 'Portugal', 'iso' => 'PT']);
                    country::create(['name' => 'Puerto Rico', 'iso' => 'PR']);
                    country::create(['name' => 'Qatar', 'iso' => 'QA']);
                    country::create(['name' => 'Réunion', 'iso' => 'RE']);
                    country::create(['name' => 'Romania', 'iso' => 'RO']);
                    country::create(['name' => 'Russian Federation', 'iso' => 'RU']);
                    country::create(['name' => 'Rwanda', 'iso' => 'RW']);
                    country::create(['name' => 'Saint Barthélemy', 'iso' => 'BL']);
                    country::create(['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso' => 'SH']);
                    country::create(['name' => 'Saint Kitts and Nevis', 'iso' => 'KN']);
                    country::create(['name' => 'Saint Lucia', 'iso' => 'LC']);
                    country::create(['name' => 'Saint Martin (French part);', 'iso' => 'MF']);
                    country::create(['name' => 'Saint Pierre and Miquelon', 'iso' => 'PM']);
                    country::create(['name' => 'Saint Vincent and the Grenadines', 'iso' => 'VC']);
                    country::create(['name' => 'Samoa', 'iso' => 'WS']);
                    country::create(['name' => 'San Marino', 'iso' => 'SM']);
                    country::create(['name' => 'Sao Tome and Principe', 'iso' => 'ST']);
                    country::create(['name' => 'Saudi Arabia', 'iso' => 'SA']);
                    country::create(['name' => 'Senegal', 'iso' => 'SN']);
                    country::create(['name' => 'Serbia', 'iso' => 'RS']);
                    country::create(['name' => 'Seychelles', 'iso' => 'SC']);
                    country::create(['name' => 'Sierra Leone', 'iso' => 'SL']);
                    country::create(['name' => 'Singapore', 'iso' => 'SG']);
                    country::create(['name' => 'Sint Maarten (Dutch part);', 'iso' => 'SX']);
                    country::create(['name' => 'Slovakia', 'iso' => 'SK']);
                    country::create(['name' => 'Slovenia', 'iso' => 'SI']);
                    country::create(['name' => 'Solomon Islands', 'iso' => 'SB']);
                    country::create(['name' => 'Somalia', 'iso' => 'SO']);
                    country::create(['name' => 'South Africa', 'iso' => 'ZA']);
                    country::create(['name' => 'South Georgia and the South Sandwich Islands', 'iso' => 'GS']);
                    country::create(['name' => 'South Sudan', 'iso' => 'SS']);
                    country::create(['name' => 'Spain', 'iso' => 'ES']);
                    country::create(['name' => 'Sri Lanka', 'iso' => 'LK']);
                    country::create(['name' => 'Sudan', 'iso' => 'SD']);
                    country::create(['name' => 'Sucountry::create(riname', 'iso' => 'SR']);
                    country::create(['name' => 'Svalbard and Jan Mayen', 'iso' => 'SJ']);
                    country::create(['name' => 'Swaziland', 'iso' => 'SZ']);
                    country::create(['name' => 'Sweden', 'iso' => 'SE']);
                    country::create(['name' => 'Switzerland', 'iso' => 'CH']);
                    country::create(['name' => 'Syrian Arab Republic', 'iso' => 'SY']);
                    country::create(['name' => 'Taiwan', 'iso' => 'TW']);
                    country::create(['name' => 'Tajikistan', 'iso' => 'TJ']);
                    country::create(['name' => 'Tanzania, United Republic of', 'iso' => 'TZ']);
                    country::create(['name' => 'Thailand', 'iso' => 'TH']);
                    country::create(['name' => 'Timor-Leste', 'iso' => 'TL']);
                    country::create(['name' => 'Togo', 'iso' => 'TG']);
                    country::create(['name' => 'Tokelau', 'iso' => 'TK']);
                    country::create(['name' => 'Tonga', 'iso' => 'TO']);
                    country::create(['name' => 'Trinidad and Tobago', 'iso' => 'TT']);
                    country::create(['name' => 'Tunisia', 'iso' => 'TN']);
                    country::create(['name' => 'Turkey', 'iso' => 'TR']);
                    country::create(['name' => 'Turkmenistan', 'iso' => 'TM']);
                    country::create(['name' => 'Turks and Caicos Islands', 'iso' => 'TC']);
                    country::create(['name' => 'Tuvalu', 'iso' => 'TV']);
                    country::create(['name' => 'Uganda', 'iso' => 'UG']);
                    country::create(['name' => 'Ukraine', 'iso' => 'UA']);
                    country::create(['name' => 'United Arab Emirates', 'iso' => 'AE']);
                    country::create(['name' => 'United Kingdom', 'iso' => 'GB']);
                    country::create(['name' => 'United States', 'iso' => 'US']);
                    country::create(['name' => 'United States Minor Outlying Islands', 'iso' => 'UM']);
                    country::create(['name' => 'Uruguay', 'iso' => 'UY']);
                    country::create(['name' => 'Uzbekistan', 'iso' => 'UZ']);
                    country::create(['name' => 'Vanuatu', 'iso' => 'VU']);
                    country::create(['name' => 'Venezuela, Bolivarian Republic of', 'iso' => 'VE']);
                    country::create(['name' => 'Viet Nam', 'iso' => 'VN']);
                    country::create(['name' => 'Virgin Islands, British', 'iso' => 'VG']);
                    country::create(['name' => 'Virgin Islands, U.S.', 'iso' => 'VI']);
                    country::create(['name' => 'Wallis and Futuna', 'iso' => 'WF']);
                    country::create(['name' => 'Western Sahara', 'iso' => 'EH']);
                    country::create(['name' => 'Yemen', 'iso' => 'YE']);
                    country::create(['name' => 'Zambia', 'iso' => 'ZM']);
                    country::create(['name' => 'Zimbabwe', 'iso' => 'ZW']);
               
            
    }
}
